# Generated by Django 5.0.6 on 2024-06-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocol_app.special', verbose_name='Специальность'),
        ),
    ]
