# Generated by Django 5.0.6 on 2024-06-22 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_app', '0002_alter_employee_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='previous_date_eb_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Предыдущая дата ЭБ'),
        ),
    ]
